//package exceptions;
//
//class ArithmeticTest {
//	public static void division(int num1, int num2) {
//		int result = num1 / num2;
//		System.out.println("Division: " + result);
//	}
//}
//
//public class ExceptionHandlingExampleOne {
//
//	public static void main(String[] args) {
//		ArithmeticTest.division(100, 0); 		// Exception
//	}
//	
//}
